Add the GPUIterator module
chapel-lang/mason-registry pull request #24
Opened 2019-07-09 17:53 UTC by ahayashi

I'd like to add the GPUIterator module, which we presented at the CHIUW2019 workshop (https://chapel-lang.org/CHIUW2019.html). The code can be found at: https://github.com/ahayashi/chapel-gpu

Please let me know if you have any questions.

Thanks,

Akihiro

2019-08-12 14:22 UTC, ben-albrecht commented on Bricks/GPUIterator/0.1.0.toml
> +authors = "Akihiro Hayashi, Sri Raj Paul, Vivek Sarkar"
```suggestion
authors = ["Akihiro Hayashi", "Sri Raj Paul", "Vivek Sarkar"]
```

2019-08-12 14:23 UTC, ben-albrecht requested changes
@ahayashi - apologies for the delay in review.

The package looks good. The only change needed is for the authors field to be a TOML array.

Thanks for contributing this package!

2019-08-12 17:46 UTC, ahayashi commented
Hi, @ben-albrecht 

No problems! Thank you for your review. I've just committed the change you requested. Please let me know if there are any further requests. 

Best regards,

Akihiro

2019-08-13 17:54 UTC, ben-albrecht approved these changes

2019-08-13 17:54 UTC, merged